[build]
  publish = "src"
  functions = "functions"

[dev]
  publish = "src"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
    from = "/env.js"
    to = "/src/env.js"
    status = 200

[build.environment]
    NODE_VERSION = "14"

[functions]
    directory = "functions"

[[headers]]
    for = "/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
    for = "/env.js"
    [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"