[build]
    publish = "src"
    functions = "netlify/functions"
    command = "cp -r netlify/functions src/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[functions]
    directory = "netlify/functions"