[build]
  publish = "src"
  functions = "netlify/functions"

[dev]
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/env.js"
  to = "/env.js"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/env.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"