[build]
  publish = "src"
  functions = "netlify/functions"

[dev]
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_OPENWEATHER_API_KEY = ${REACT_APP_OPENWEATHER_API_KEY}
  REACT_APP_GOOGLE_MAPS_API_KEY = ${REACT_APP_GOOGLE_MAPS_API_KEY}

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/env.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"