[build]
  publish = "src"
  functions = "functions"

[dev]
  publish = "src"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
    NODE_VERSION = "14"

[functions]
    directory = "functions"

[[headers]]
    for = "/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"